#ifndef ERRORNUMBERS_H_INCLUDED
#define ERRORNUMBERS_H_INCLUDED

#define OK              100
#define OUT_OF_MEMORY   110
#define DUPLICATED_KEY  120
#define IS_NULL         130

#endif // ERRORNUMBERS_H_INCLUDED
